### ISSUE TITLE
The backbone networks need to be reproduced and  more can see TODO List & Currently Supported Models

### ISSUE THREAD

**Issue by Jittor-Image-Models** [Timm-Jittor/Jittor-Image-Models#1]
- [ ] Big Transfer ResNetV2 (BiT) - https://arxiv.org/abs/1912.11370
- [ ] Bottleneck Transformers - https://arxiv.org/abs/2101.11605
- [ ] CaiT (Class-Attention in Image Transformers) - https://arxiv.org/abs/2103.17239
- [ ] CoaT (Co-Scale Conv-Attentional Image Transformers) - https://arxiv.org/abs/2104.06399
- [ ] ConViT (Soft Convolutional Inductive Biases Vision Transformers)- https://arxiv.org/abs/2103.10697
- [ ] CspNet (Cross-Stage Partial Networks) - https://arxiv.org/abs/1911.11929
- [x] DeiT (Vision Transformer) - https://arxiv.org/abs/2012.12877
- [ ] DenseNet - https://arxiv.org/abs/1608.06993
- [ ] DLA - https://arxiv.org/abs/1707.06484
- [ ] DPN (Dual-Path Network) - https://arxiv.org/abs/1707.01629
- [ ] EfficientNet (MBConvNet Family)
    - [x] EfficientNet NoisyStudent (B0-B7, L2) - https://arxiv.org/abs/1911.04252
    - [x] EfficientNet AdvProp (B0-B8) - https://arxiv.org/abs/1911.09665
    - [x] EfficientNet (B0-B7) - https://arxiv.org/abs/1905.11946
    - [ ] EfficientNet-EdgeTPU (S, M, L) - https://ai.googleblog.com/2019/08/efficientnet-edgetpu-creating.html
    - [x] EfficientNet V2 - https://arxiv.org/abs/2104.00298
    - [ ] FBNet-C - https://arxiv.org/abs/1812.03443
    - [ ] MixNet - https://arxiv.org/abs/1907.09595
    - [ ] MNASNet B1, A1 (Squeeze-Excite), and Small - https://arxiv.org/abs/1807.11626
    - [ ] MobileNet-V2 - https://arxiv.org/abs/1801.04381
    - [ ] Single-Path NAS - https://arxiv.org/abs/1904.02877
- [ ] GhostNet - https://arxiv.org/abs/1911.11907
- [ ] gMLP - https://arxiv.org/abs/2105.08050
- [ ] GPU-Efficient Networks - https://arxiv.org/abs/2006.14090
- [ ] Halo Nets - https://arxiv.org/abs/2103.12731
- [ ] HardCoRe-NAS - https://arxiv.org/abs/2102.11646
- [x] HRNet - https://arxiv.org/abs/1908.07919
- [ ] Inception-V3 - https://arxiv.org/abs/1512.00567
- [ ] Inception-ResNet-V2 and Inception-V4 - https://arxiv.org/abs/1602.07261
- [ ] Lambda Networks - https://arxiv.org/abs/2102.08602
- [ ] LeViT (Vision Transformer in ConvNet's Clothing) - https://arxiv.org/abs/2104.01136
- [ ] MLP-Mixer - https://arxiv.org/abs/2105.01601
- [ ] MobileNet-V3 (MBConvNet w/ Efficient Head) - https://arxiv.org/abs/1905.02244
- [ ] NASNet-A - https://arxiv.org/abs/1707.07012
- [ ] NFNet-F - https://arxiv.org/abs/2102.06171
- [ ] NF-RegNet / NF-ResNet - https://arxiv.org/abs/2101.08692
- [ ] PNasNet - https://arxiv.org/abs/1712.00559
- [ ] Pooling-based Vision Transformer (PiT) - https://arxiv.org/abs/2103.16302
- [ ] RegNet - https://arxiv.org/abs/2003.13678
- [ ] RepVGG - https://arxiv.org/abs/2101.03697
- [ ] ResMLP - https://arxiv.org/abs/2105.03404
- [ ] ResNet/ResNeXt
    - [x] ResNet (v1b/v1.5) - https://arxiv.org/abs/1512.03385
    - [x] ResNeXt - https://arxiv.org/abs/1611.05431
    - [ ] 'Bag of Tricks' / Gluon C, D, E, S variations - https://arxiv.org/abs/1812.01187
    - [x] Weakly-supervised (WSL) Instagram pretrained / ImageNet tuned ResNeXt101 - https://arxiv.org/abs/1805.00932
    - [x] Semi-supervised (SSL) / Semi-weakly Supervised (SWSL) ResNet/ResNeXts - https://arxiv.org/abs/1905.00546
    - [ ] ECA-Net (ECAResNet) - https://arxiv.org/abs/1910.03151v4
    - [ ] Squeeze-and-Excitation Networks (SEResNet) - https://arxiv.org/abs/1709.01507
    - [ ] ResNet-RS - https://arxiv.org/abs/2103.07579
- [ ] Res2Net - https://arxiv.org/abs/1904.01169
- [ ] ResNeSt - https://arxiv.org/abs/2004.08955
- [ ] ReXNet - https://arxiv.org/abs/2007.00992
- [ ] SelecSLS - https://arxiv.org/abs/1907.00837
- [ ] Selective Kernel Networks - https://arxiv.org/abs/1903.06586
- [x] Swin Transformer - https://arxiv.org/abs/2103.14030
- [ ] Transformer-iN-Transformer (TNT) - https://arxiv.org/abs/2103.00112
- [ ] TResNet - https://arxiv.org/abs/2003.13630
- [ ] Twins (Spatial Attention in Vision Transformers) - https://arxiv.org/pdf/2104.13840.pdf
- [x] Vision Transformer - https://arxiv.org/abs/2010.11929
- [ ] VovNet V2 and V1 - https://arxiv.org/abs/1911.06667
- [ ] Xception - https://arxiv.org/abs/1610.02357
- [ ] Xception (Modified Aligned, Gluon) - https://arxiv.org/abs/1802.02611
- [ ] Xception (Modified Aligned, TF) - https://arxiv.org/abs/1802.02611

Some old backbone networks may have a lower priority for reproducing, we will pay more attention on the update news  in timm.
